### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by Surendrajat** [FunkyMuse/Aurora#37]
`` Stacktrace ``

java.lang.IllegalStateException: You cannot access the NavBackStackEntry's ViewModels until it is added to the NavController's back stack (i.e., the Lifecycle of the NavBackStackEntry reaches the CREATED state).
	at v3.f.h(:4)
	at a2.a.k(:2)
	at w3.k.b(:1)
	at w3.k$a.I(:1)
	at n0.b.I(:1)
	at g0.v.a(Unknown Source:30)
	at w3.k.a(:5)
	at w3.t$b.H(:1)
	at n0.b.a(Unknown Source:48)
	at n0.b.H(Unknown Source:8)
	at r.u$a.I(:17)
	at n0.b.I(:1)
	at r.u.a(:26)
	at w3.t.b(:104)
	at w3.t$c.I(:1)
	at g0.i.h0(:27)
	at g0.i.s(:6)
	at g0.i$h.p(:8)
	at g0.b2.f(:4)
	at g0.i.V(:12)
	at g0.i.g0(:2)
	at g0.s.q(:2)
	at g0.h1.o(:5)
	at g0.n1$a.L(:24)
	at i1.a0$c.doFrame(Unknown Source:8)
	at i1.z.doFrame(:3)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1092)
	at android.view.Choreographer.doCallbacks(Choreographer.java:917)
	at android.view.Choreographer.doFrame(Choreographer.java:840)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1079)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:238)
	at android.app.ActivityThread.main(ActivityThread.java:7798)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)

`` END of stacktrace ``

`` Thread info ``

Name: main
ID: 2
State: RUNNABLE
Priority: 5
Thread group name: main
Thread group parent: system
Thread group active count: 42
Thread time: 0 hr 0 min, 14 sec

`` END of thread info ``

`` Device info ``

Report ID: ac7a97c1-b4b4-4592-8169-8e65a2a94943
Device ID: *removed*
Application version: 3
Default launcher: com.saggitt.omega.dev
Timezone name: India Standard Time
Timezone ID: Asia/Kolkata
Version release: 10
Version incremental : 1610416061
Version SDK: 29
Board: sdm710
Bootloader: unknown
Brand: OPPO
CPU ABIS 32: armeabi-v7a, armeabi
CPU ABIS 64: arm64-v8a
Supported ABIS: arm64-v8a, armeabi-v7a, armeabi
Device: OP486B
Display: CPH1955EX_11_C.14
Fingerprint: OPPO/CPH1955/OP486B:10/QKQ1.190918.001/1610416061:user/release-keys
Hardware: qcom
Host: CP-ubuntu-123
ID: QKQ1.190918.001
Manufacturer: OPPO
Product: CPH1955
Build time: 1611348931000
Build time formatted: 23-01-2021 02:25:31
Type: user
Radio: Q_V1_P14,Q_V1_P14
Tags: release-keys
User: root
User IDs: N/A
Is sustained performance mode supported: No
Is in power save mode: Yes
Is in interactive state: Yes
Is ignoring battery optimizations: No
Thermal status: STATUS_NONE
Location power save mode: MODE_NO_CHANGE
Is device idle: No
Battery percentage: 37
Battery remaining time: N/A
Is battery charging: No
Is device rooted: No
CPU Model: Qualcomm Technologies, Inc SDM710
Number of CPU cores: 8
Up time with sleep: 463 hr 7 min, 17 sec
Up time without sleep: 188 hr 42 min, 19 sec

`` END of Device info ``

`` Exit reasons ``

N/A

`` END of exit reasons ``

`` Application info ``

App name: Aurora
Version code: 3
Version name: 1.1.1
Package name: com.funkymuse.aurora
Short package name: aurora
Flavor: N/A
Signatures: qSF/RHPYjm2Y7vNqAZ7ehzvKqVg=
Is debuggable: No
First installed: 14-08-2021 17:41:58
Last updated: 14-08-2021 17:41:58
Requested permissions: android.permission.INTERNET, android.permission.ACCESS_NETWORK_STATE, android.permission.ACCESS_WIFI_STATE
Default prefs: N/A
Default prefs: N/A

`` END of Application info ``

`` Currently running foreground/background processes ``

N/A

`` END of running foreground/background processes info ``

**Comment by FunkyMuse** [comment]
Thanks for reporting

Connected to:
issuetracker.google.com/issues/195860509, issuetracker.google.com/issues/195687654.

**Comment by FunkyMuse** [comment]
Will be fixed in 1.2.0 which will be released later tonight
